#!/bin/bash
set -o nounset
set -o errexit

role=$1
ext="-Y EXTERNAL -H ldapi:///"
admin="-x -D cn=admin,dc=federez,dc=net -W -H ldapi:///"

. ./dist/debian

install_ldap ./dist/debconf

# dc=federez,dc=net
#sudo ldapadd -Y EXTERNAL -H ldapi:/// -f ./federez.net/base.ldif
ldapadd $admin -f ./federez.net/ou.ldif

# netFederez schema
sudo ldapadd $ext -f ./conf/schema/netfederez.ldif

# memberof
sudo ldapmodify $ext -f ./conf/overlay/memberof.ldif

# dyngroup
sudo ldapadd $ext -f /etc/ldap/schema/dyngroup.ldif
sudo ldapmodify $ext -f ./conf/overlay/dynlist.ldif

# ppolicy
sudo ldapadd $ext -f /etc/ldap/schema/ppolicy.ldif
sudo ldapmodify $ext -f ./conf/overlay/ppolicy.ldif
ldapmodify $admin -f ./conf/overlay/ppolicy_policies.ldif

sudo ldapmodify $ext -f ./conf/overlay/unique.ldif
sudo ldapmodify $ext -f ./conf/overlay/refint.ldif

ldapadd $admin -f ./conf/sync/syncuser.ldif

case "$role" in
    provider)
        sudo ldapadd $ext -f ./conf/sync/provider.ldif
        ;;
    consumer)
        sudo ldapadd $ext -f ./conf/sync/consumer.ldif
        ;;
    nosync)
        ;;
    *)
        echo "Error: First argument must be consumer or provider"
        exit 1
esac

ldapadd $admin -f ./test/users.ldif

install_webldap "$(pwd)/webldap/local_settings.py"
